### ISSUE TITLE
`Column::cell` doesn't allow output to borrow from row argument

### ISSUE THREAD

**Issue by chinoto** [tarkah/iced_table#2]
I was optimizing away some allocations and ran into "lifetime may not live long enough" when attempting to borrow Strings for use in `Text::new`. The issue stems from the arguments of `Column::cell` belonging to lifetime `'b` and the output belonging to lifetime `'a`.
Here's a minimal example of the change I attempted that triggered this:
```diff
- Text::new(row.name.clone())
+ Text::new(&row.name)
```

I suspect that the reasoning for this might be to allow the output to exist while allowing self/row to be mutated after the method is called?

https://github.com/tarkah/iced_table/blob/7d62b27c0a4771fd4a1497dc6056bbdc26e906f3/src/lib.rs#L61-L66

**Comment by tarkah** [comment]
Yes 'b is shorter than 'a. This is because 'b is the short lifetime of your Column struct when passed in during view to create the table widget, where Column is then dropped. It's not held past it's call site in view.

'a is lifetime from your application state that lives for the application.

The struct you implement Column on can borrow from your application the string you want for 'a and this should work, since an 'a borrow behind a 'b borrow is still valid for 'a

**Comment by tarkah** [comment]
Yeah so disregard what I said before. My memory was off some other implementation which appears I left some artifacts for.

Since we take `&'a [Row] / &'a [Column]` in `view` there's no reason we shouldn't just pass in `&'a Row` / `&'a self` in `Column` trait members, which enables us to borrow from it for the returned `Element<'a>`.

I've fixed this and shipped an update for `iced_table 0.2.0`, thanks!
